--
--  toyboxes.lua - include file auto-generated by toybox.py (https://toyboxpy.io).
--

import 'github-dot-com/Whitebrim/AnimatedSprite/AnimatedSprite.lua'
import 'codeberg-dot-org/DidierMalenfant/Signal/Signal.lua'
import 'github-dot-com/NicMagnier/PlaydateSequence/sequence.lua'
import 'github-dot-com/RobertCurry0216/roomy-playdate/roomy-playdate.lua'
